blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/l2D/assignment-java-boot-camp/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
