name: Run test

on:
  push:
    branches:
    - main
    - development
    - fix-*
    - feat-*
  pull_request:
    branches:
    - main
    - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Testing
      run: mvn test -f ./assignments/week1/
